all:
	g++ -o Driver Driver.cpp *.o -std=c++11
Cell.o:
	g++ -o Cell.o -c Cell.cpp -std=c++11
Habitat.o:
	g++ -o Habitat.o -c Habitat.cpp -std=c++11
Facility.o:
	g++ -o Facility.o -c Facility.cpp -std=c++11
LandHabitat.o:
	g++ -o LandHabitat.o -c LandHabitat.cpp -std=c++11
WaterHabitat.o:
	g++ -o WaterHabitat.o -c WaterHabitat.cpp -std=c++11
AirHabitat.o:
	g++ -o AirHabitat.o -c AirHabitat.cpp -std=c++11
Restourant.o:
	g++ -o Restourant.o -c Restourant.cpp -std=c++11
Road.o:
	g++ -o Road.o -c Road.cpp -std=c++11
Exit.o:
	g++ -o Exit.o -c Exit.cpp -std=c++11
Entrance.o:
	g++ -o Entrance.o -c Entrance.cpp -std=c++11
Animal.o:
	g++ -o Animal.o -c Animal.cpp -std=c++11
LandAnimal.o:
	g++ -o LandAnimal.o -c LandAnimal.cpp -std=c++11
WaterAnimal.o:
	g++ -o WaterAnimal.o -c WaterAnimal.cpp -std=c++11
FlyingAnimal.o:
	g++ -o FlyingAnimal.o -c FlyingAnimal.cpp -std=c++11
Cat.o:
	g++ -o Cat.o -c Cat.cpp -std=c++11
Dog.o:
	g++ -o Dog.o -c Dog.cpp -std=c++11
